### PR TITLE
fix for issue #7

### PR DESCRIPTION
**Pull request by schBen**

### CODE REVIEW

**Comment by pomadchin** [comment]
Can we set locale using jvm args? For example: `-Duser.language=en -Duser.region=US`

Adding into `build.sbt`:

``` scala
javacOptions ++= Seq("-Duser.language=en", "-Duser.region=US")
```

**Comment by jamesmcclain** [comment]
@pomadchin Yes, I addressed a somewhat similar issue in GeoTrellis some time ago with [this](https://github.com/geotrellis/geotrellis/pull/1466/files) fix.  The fix you suggested seems like it should work.

**Comment by lossyrob** [comment]
@pomadchin does that fix work at compile time, or would there be some run time settings set?

**Comment by pomadchin** [comment]
@lossyrob would check it, got you thought

**Comment by pomadchin** [comment]
Finally JRE locale setting can be changed using following:
- Using [Locale.setDefault()](http://docs.oracle.com/javase/7/docs/api/java/util/Locale.html#setDefault%28java.util.Locale%29)
  
  ``` scala
  Locale.setDefault(new Locale("en", "US"));
  ```
- Via arguments to the JVM:
  
  ```
  java -jar assembly.jar -Duser.language=en-US
  ```

I think it is more a client app setting rather than current code problems.

**Comment by hjaekel** [comment]
@pomadchin It may be that other parts of the application should be localized, setting the en-US locale as default would prevent this. Formatting of the query parameters should independent of the current localisation. So I would prefer not to use the default locale to fix this problem.

**Comment by pomadchin** [comment]
@hjaekel hm, it makes sense; @schBen can you update this pr?

**Comment by schBen** [comment]
@pomadchin Okay, pr is up to date.

**Comment by pomadchin** [comment]
@schBen thanks!

**Review by pomadchin — APPROVED** [review]

**Pull request merged**
