### PR TITLE
Converted Spray.io to Akka HTTP

### PR DESCRIPTION
**Pull request by metasim**
I'm trying to keep my system consistently using Akka HTTP, and would like to use this library, so I ported the HTTP client part over. Not sure if this fits with your technology plan, and understand if you don't want this PR, but offer it up if there's interest.

I note in some comments that there are a few areas of improvement in more efficiently managing the HTTP requests, and may try to address them next.

### CODE REVIEW

**Review by pomadchin — COMMENTED** [review]
Awesome, though I am not sure that it is useful to keep gt deps as not provided, at least for the moment we have no stable major release.

**Comment by metasim** [comment]
The `gtMode` value should default to `provided`. I mainly provided that environment variable so I could run the tests/examples in the project by itself. Is there a better way of doing that?

**Comment by pomadchin** [comment]
@metasim you can use [either function](https://github.com/locationtech/geotrellis/blob/master/project/Environment.scala#L20) but i see no reasons why we should pack geotrellis inside? As with "provided" we can depend on all API compatible gt versions, and packing gt versions inside may cause versions mismatch issues.

**Comment by metasim** [comment]
@pomadchin I like the "either function". Nice technique; are you suggesting it should be copied to this repo?

With respect to `provided` vs. `compiled` (the sbt default), my intent was just to make GT available when I run `com.azavea.landsatutil.Examples` from the IDE or sbt. Neither `provided` nor `compiled` will "pack" the dependency inside the final package (unless you use `sbt-assembly` which isn't really relevant here), so I'm not sure I know what you mean there. The `provided` dependency scope makes sure the dependency is available for compilation, but doesn't add it transitively in the runtime classpath  (assumes it will be provided via some other means). Specifying`compile`, ironically, makes sure the dependency is available for both compilation _and_ runtime. The sbt docs aren't great on this topic, but the corresponding [Maven docs](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Scope) do a pretty good job of describing the behavior.

That said, I can just remove the switch hack and put "provided" back as it was. I would be curious to know how you get your IDE/sbt to "provide" the dependency when running the `Examples` class. This is what I get:

```scala
scala-landsat-util > run
[info] Running com.azavea.landsatutil.Examples 
[error] (run-main-0) java.lang.NoClassDefFoundError: geotrellis/vector/Geometry
java.lang.NoClassDefFoundError: geotrellis/vector/Geometry
	at com.azavea.landsatutil.Examples.main(Examples.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
Caused by: java.lang.ClassNotFoundException: geotrellis.vector.Geometry
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.azavea.landsatutil.Examples.main(Examples.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
[trace] Stack trace suppressed: run last compile:run for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
	at scala.sys.package$.error(package.scala:27)
```

**Comment by pomadchin** [comment]
@metasim right, you need to add geotrellis deps explicitly into your project. 

Example:

```scala
"com.azavea.geotrellis"  %% "geotrellis-vector" % Version.geotrellis,
"com.azavea.geotrellis"  %% "geotrellis-raster" % Version.geotrellis,
"com.azavea"  %% "scala-landsat-util" % Version.scalaLandsatUtil
```

**Comment by lossyrob** [comment]
Superseded by #17

**Pull request closed without merging**
